[package]
name = "union_peaks"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
flate2 = "1.0.27"
clap = { version = "3.0.14", features = ["derive"] }
