name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      # 1. Check out your code
      - uses: actions/checkout@v4

      # 3. Set up Rust
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      # 4. Build and run tests
      - name: Build
        run: cargo build --verbose
      - name: Test
        run: cargo test --verbose
